/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccineregistrationsystem;

import javax.swing.JOptionPane;
import vaccineregistrationsystem.VaccineRegistrationSystem.AccessMode;

/**
 *
 * @author DELL
 */
public class PeopleDetailPage extends javax.swing.JFrame {

    /**
     * Creates new form PeopleDetailPage
     */
    private int peopleID;
    private People people;
    private AccessMode mode;
    
    
    public PeopleDetailPage(AccessMode mode, int peopleID) {
        initComponents();
        this.setVisible(true);
        this.peopleID = peopleID;
        this.mode = mode;
        btnEdit.setVisible(false);
        
        lblPeopleID.setText(String.valueOf(peopleID));
        
        if(mode != AccessMode.NEW){
           displayDetails(); 
        }else{
            jLabel1.setVisible(false);
            lblPeopleID.setVisible(false);
            btnSave.setText("Register");
            people = new People();
        }
        
        if(mode == AccessMode.VIEW){
            enterViewMode();
        }
        
    }
      
    private void displayDetails(){
        people = People.getPeopleByID(peopleID);
        
        txtName.setText(people.getName());
        txtIC.setText(people.getNric());
        txtPhoneNo.setText(people.getPhoneNo());
        txtPasswd.setText(people.getPasswd());
        txtAddress.setText(UIUtils.decodeMultiLineText(people.getAddress()));
        txtPostCode.setText(String.valueOf(people.getPostCode()));
        
        chkCitizen.setSelected(people.isCitizenship());
        
        txtIC.setEditable(false);
    }
    
    private void enterViewMode(){
        txtName.setEditable(false);
        txtIC.setEditable(false);
        txtPhoneNo.setEditable(false);
        txtPasswd.setEditable(false);
        txtAddress.setEditable(false);
        txtPostCode.setEditable(false);
        
        chkCitizen.setEnabled(false);
        btnSave.setVisible(false);
        btnGeneratePasswd.setVisible(false);
    }
    
    public void PeopleEdit(){
        btnEdit.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtIC = new javax.swing.JTextField();
        txtPasswd = new javax.swing.JTextField();
        txtPhoneNo = new javax.swing.JTextField();
        txtPostCode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chkCitizen = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        btnGeneratePasswd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        lblPeopleID = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("People Detail");

        jLabel1.setText("People ID");

        jLabel2.setText("IC/ Passport No");

        jLabel3.setText("Password");

        jLabel4.setText("Phone Number");

        jLabel5.setText("Address");

        jLabel6.setText("PostCode");

        jLabel7.setText("Citizenship");
        jLabel7.setToolTipText("");

        chkCitizen.setSelected(true);
        chkCitizen.setText("Is Citizen");

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setText("People Details");
        jLabel8.setToolTipText("");

        btnGeneratePasswd.setBackground(new java.awt.Color(93, 93, 90));
        btnGeneratePasswd.setForeground(new java.awt.Color(255, 255, 255));
        btnGeneratePasswd.setText("Generate");
        btnGeneratePasswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratePasswdActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(93, 93, 90));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jLabel9.setText("Name");

        lblPeopleID.setText("XXX");

        btnEdit.setBackground(new java.awt.Color(93, 93, 90));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit Profile");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEdit)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIC, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPeopleID)
                                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGeneratePasswd))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(40, 40, 40)
                                .addComponent(chkCitizen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(268, 268, 268)))
                        .addGap(16, 37, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3)
                        .addGap(0, 377, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPeopleID)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGeneratePasswd))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCitizen)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnEdit))
                .addGap(59, 59, 59))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(validateInput()){
            //Save
            people.setUserID(peopleID);
            people.setName(txtName.getText());
            people.setNric(txtIC.getText());
            people.setPasswd(txtPasswd.getText());
            people.setPhoneNo(txtPhoneNo.getText());
            people.setPostCode(Integer.parseInt(txtPostCode.getText()));
            String address = UIUtils.encodeMultiLineText(txtAddress.getText());
            people.setAddress(address);
            people.setCitizenship(chkCitizen.isSelected());
            
            if(mode == AccessMode.EDIT){
                people.update();
            }else{
                people.register();
            }
            
            this.dispose();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnGeneratePasswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePasswdActionPerformed
        String name = txtName.getText();
        
        String phoneNo = txtPhoneNo.getText();
        
        if(name.trim().equals("") || phoneNo.trim().equals("")){
                        JOptionPane.showMessageDialog(null, "Require Name and Phone No to generate password", 
                                "Invalid Input", JOptionPane.WARNING_MESSAGE);

            return;
        }
        
        String surname = name.split(" ")[0];
        String password = surname + phoneNo;
        
        txtPasswd.setText(password);
        
    }//GEN-LAST:event_btnGeneratePasswdActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PeopleDetailPage x = new PeopleDetailPage(AccessMode.EDIT,peopleID);
    }//GEN-LAST:event_btnEditActionPerformed

    private boolean validateInput(){
        String message = "";
        boolean valid = true;
        
        String password = txtPasswd.getText();
        String phoneNo = txtPhoneNo.getText();
        String postCode = txtPostCode.getText();
        String ic = txtIC.getText();
        String name = txtName.getText();
        String add = txtAddress.getText();
        
        if(UIUtils.isInputBlank(ic)){
            message = "IC/Passport No cannot be blank";
            valid = false;
        }
        
        if(UIUtils.isInputBlank(name)){
            message = "Name cannot be blank";
            valid = false;
        }
        
        if(UIUtils.isInputBlank(add)){
            message = "Address cannot be blank";
            valid = false;
        }
        
        if(!UIUtils.checkPasswordValid(password)){
            message = "Invalid Password. Minimum password length is 6";
            valid = false;
        }
        
        if(!UIUtils.checkPostcodeValid(postCode)){
            message = "Invalid PostCode";
            valid = false;
        }
        
        if(!UIUtils.checkPhoneNumberValid(phoneNo)){
            message = "Invalid Phone Number";
            valid = false;
        }
        
        boolean icduplicated;
        
        if(mode == AccessMode.EDIT){
            icduplicated = People.checkIfICExisted(ic,peopleID);
        }else{
            icduplicated = People.checkIfICExisted(ic);
        }
        
        if(icduplicated){
            message = "IC/Passport Number Existed";
            valid = false;
        }
        
        if(!valid){
            JOptionPane.showMessageDialog(null, message, "Invalid Input", JOptionPane.WARNING_MESSAGE);
        }
        
        return valid;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeopleDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeopleDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeopleDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeopleDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnGeneratePasswd;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkCitizen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPeopleID;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtIC;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPasswd;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtPostCode;
    // End of variables declaration//GEN-END:variables
}
