/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccineregistrationsystem;

import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.Component;
import java.util.Date;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.text.JTextComponent;
import vaccineregistrationsystem.VaccineRegistrationSystem.AccessMode;

/**
 *
 * @author DELL
 */
public class VaccineDetailPage extends javax.swing.JFrame {

    /**
     * Creates new form VaccineDetailPage
     */
    private AccessMode mode;
    private int vaccineID;
    private Vaccine vaccine;
    
    public VaccineDetailPage(AccessMode mode, int vaccineID) {
        initComponents();
        this.setVisible(true);
        
        this.mode = mode;
        this.vaccineID = vaccineID;
        
        if(mode != AccessMode.NEW){
           displayDetails(); 
        }else{
            vaccine = new Vaccine();
            txtAppointed.setText("0");
        }
        
        if(mode == AccessMode.VIEW){
            enterViewMode();
        }
        
        if(mode == AccessMode.EDIT){
            restrictEdit();
        }
    }
    
    private void restrictEdit(){
        // Once the vaccine has been used for appointment cannot chg expire date and centre
        if(vaccine.getAppointedAmt() > 0){
            cboCentre.setEnabled(false);
            dateExp.setEnabled(false);
            cboName.setEnabled(false);
        
            ((JTextFieldDateEditor)dateExp.getDateEditor())
                .setDisabledTextColor(Color.darkGray);
            UIManager.put( "ComboBox.disabledForeground", Color.BLACK );

        }
    }
    
    private void displayDetails(){
        vaccine = Vaccine.searchVaccine(vaccineID);
        
        int centreID = vaccine.getCentreID();
        
        cboName.setSelectedItem(vaccine.getVaccineName());
        txtBalance.setText(String.valueOf(vaccine.getBalance()));
        txtAppointed.setText(String.valueOf(vaccine.getAppointedAmt()));
        cboCentre.setSelectedItem(Centre.searchByID(centreID).getCentreName());
        dateExp.setDate(vaccine.getExpDate());
        
        
    }
    
    private void enterViewMode(){
        cboName.setEnabled(false);
        txtBalance.setEditable(false);
        cboCentre.setEnabled(false);
        dateExp.setEnabled(false);
        
        ((JTextFieldDateEditor)dateExp.getDateEditor())
                .setDisabledTextColor(Color.darkGray);
        UIManager.put( "ComboBox.disabledForeground", Color.BLACK );
        
        btnSave.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateExp = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAppointed = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cboName = new javax.swing.JComboBox<>();
        cboCentre = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vaccine Detail");

        dateExp.setDateFormatString("dd-MM-yyyy");

        jLabel1.setText("Vaccine Name");

        jLabel2.setText("Balance");

        jLabel3.setText("Appointed");

        jLabel4.setText("Centre");

        jLabel5.setText("Expire Date");

        txtAppointed.setEditable(false);

        btnSave.setText("Save");
        btnSave.setBackground(new java.awt.Color(93, 93, 90));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel6.setText("Vaccine Details");
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N

        cboName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pfizer", "AstraZeneca", "Sinovac" }));

        cboCentre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "National Stadium Bukit Jalil", "KL General Hospital", "Titiwangsa Stadium", "Pending Assigned" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnSave))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel1))
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cboName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboCentre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBalance)
                                .addComponent(txtAppointed)
                                .addComponent(dateExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAppointed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(dateExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnSave)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       if(inputValidate()){
           vaccine.setVaccineID(vaccineID);
           vaccine.setBalance(Integer.parseInt(txtBalance.getText()));
           vaccine.setExpDate(dateExp.getDate());
           vaccine.setVaccineName(cboName.getSelectedItem().toString());
           vaccine.setCentreID(cboCentre.getSelectedIndex() + 1);
           
           if(mode == AccessMode.EDIT){
               vaccine.updateVaccine();
           }else if(mode == AccessMode.NEW){
               vaccine.addVaccine();
               
           }
           
           this.dispose();
       }
    }//GEN-LAST:event_btnSaveActionPerformed

    private boolean inputValidate(){
        String balance = txtBalance.getText();
        String appointAmt = txtAppointed.getText();
        
        boolean result = true;
        String message = "";
        
        if(!UIUtils.isInteger(balance)){
            result = false;
            message = "Balance must be a number";
        }
        
        if(UIUtils.isInteger(balance)){
            if(Integer.parseInt(balance) < Integer.parseInt(appointAmt)){
                result = false;
                message = "Balance cannot be less than appointed amount. Please revise the stock";
            }
            
            if(mode == AccessMode.NEW && Integer.parseInt(balance) == 0){
                result = false;
                message = "Balance invalid";
            }
        }
        
        Date expDate = dateExp.getDate();
        
        if(expDate == null){
            result = false;
            message = "Invalid Expired Date";
        }
         
        if(mode == AccessMode.NEW && expDate != null){
            Date today = new Date();
            if(!UIUtils.isToday(expDate) && expDate.before(today) ){
                result = false;
                message = "Invalid Expired Date"; 
            }
           
        }
        
        
        if(!result){
            JOptionPane.showMessageDialog(null, message, "Invalid Input", JOptionPane.WARNING_MESSAGE);
        }
        
        return result;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VaccineDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VaccineDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VaccineDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VaccineDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cboCentre;
    private javax.swing.JComboBox<String> cboName;
    private com.toedter.calendar.JDateChooser dateExp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAppointed;
    private javax.swing.JTextField txtBalance;
    // End of variables declaration//GEN-END:variables
}
